/////error, try, catch, throw 


try{
    console.log(eval("%12+3+6*7"));
}

catch(error){
    console.log("exception occured");
}

console.log("fetch call");
console.log("database commit");



